### ISSUE TITLE
[Critical] LynxHR will connect to Pixel 5's or other devices nearby which will cause a fail to connect

### ISSUE THREAD

**Issue by lunarlynix** [Furred/LynxHR#1]
**Critical**

LynxHR Automatically scans for known watches using it's feature to filter out via UUIDs but some devices uses the same UUIDs, It needs to be more strict filter for this to be fixed.

Devices Affecting / How to Replicate (Have Device Nearby) : 
**Google Home**
**Google Pixel**

**Comment by lunarlynix** [comment]
![image](https://user-images.githubusercontent.com/81735347/207766189-79c2289b-354d-4558-abae-66d74b30d2c1.png)
This is what happens when you have a device connected nearby to the watch (Normal not a bug).

If the device is found nearby LynxHR it will connect succesfully and attempt a authentication with that device, and will fail. At certain times it may affect the device.

**Comment by lunarlynix** [comment]
Potentially Fixed

**Comment by franko-fox** [comment]
Issue will be fixed by separating device discovery and connection. A first discovery step will be required to obtain a list of devices, then the correct one can be used to actually run the program, with the advantage that we can choose by MAC, to avoid trying to connect to other devices.

**Comment by lunarlynix** [comment]
Issue was fixed.
